services:
  jenkins:
    image: 541441380680.dkr.ecr.eu-central-1.amazonaws.com/jenkins-server:latest
    container_name: jenkins-compose
    restart: on-failure
    networks:
      - jenkins-compose
    environment:
      - DOCKER_HOST=tcp://docker:2375
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - ../ansible:/playbooks-vol
      - ./ssl:/var/jenkins_home/.ssh
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker-compose
    privileged: true
    networks:
      jenkins-compose:
        aliases:
          - docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2375:2375"
    command: ["dockerd", "--host=tcp://0.0.0.0:2375", "--storage-driver=overlay2", "--tls=false"]
      #  ansible:
      #image: 541441380680.dkr.ecr.eu-central-1.amazonaws.com/ansible-server:latest
      #container_name: ansible-compose
      #restart: on-failure
      #networks:
      #jenkins-compose:
      #  aliases:
      #    - ansible

      #    environment:
      #- ANSIBLE_HOST_KEY_CHECKING=False
      #volumes:
      #- ../ansible/playbooks:/ansible/playbooks

networks:
  jenkins-compose:
    driver: bridge

volumes:
  jenkins-data:
    external: true

